# -*- coding: utf-8 -*-
"""Copia de  Exámen1.2ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1znKgg_AQwpnGmPKsP9TrGtNxsY0EZxMn

# Exámen 1.2

Para archivo "microretailer_mit_lift_lab.xlsx"
"""

#Importamos librería 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#cargar un archivo xlsx desde el quipo
from google.colab import files
files.upload()

#cargar desde un archivo .xls sin indice
Retailers= pd.read_excel('microretailer_mit_lift_lab.xlsx')
Retailers.head(20)

#indentificar valores nulos por columnas 
valores_nulos=Retailers.isnull().sum()
valores_nulos

#indentificar valores nulos por columnas 
valores_nulos=Retailers.isnull().sum().sum()
valores_nulos

Retailers_Sin_Nulos=Retailers.copy()
Retailers_Sin_Nulos=Retailers_Sin_Nulos.fillna(method='bfill')
Retailers_Sin_Nulos

#indentificar valores nulos por columnas 
valores_nulos=Retailers_Sin_Nulos.isnull().sum().sum()
valores_nulos

Retailers_Sin_Nulos1=Retailers_Sin_Nulos.copy()
Retailers_Sin_Nulos1=Retailers_Sin_Nulos1.fillna(method='ffill')
Retailers_Sin_Nulos1

#indentificar valores nulos por columnas 
valores_nulos=Retailers_Sin_Nulos1.isnull().sum().sum()
valores_nulos

#indentificar valores nulos por columnas 
valores_nulos=Retailers_Sin_Nulos1.isnull().sum()
valores_nulos.head(53)

#Al observar que las únicas columnas con 171 nulos de 172 filas por lo que se considera que a se les debería cambiar por el estring "Sin respuesa"

#cuarto método de sustitución
#sustituyo los valores nulos por un string en concreto
Retailers_Sin_Nulos1=Retailers_Sin_Nulos1.fillna("Sin Respuesta")
Retailers_Sin_Nulos1

#indentificar valores nulos totales
valores_nulos=Retailers_Sin_Nulos1.isnull().sum().sum()
valores_nulos

#convertir a archivo xlsx
Retailers_Sin_Nulos1.to_excel("Retailers_Sin_Nulos.xlsx")

#descargar archivo filtrado en xlsx
from google.colab import files
files.download("Retailers_Sin_Nulos.xlsx")

"""# Sustitución de Outliers"""

Retailers_Filtrado=Retailers_Sin_Nulos1.copy()

#Identificamos las variables no numéricas para eliminar columnas incecesarias 
#Verificamos información del DataFrame
Retailers_Filtrado.info(106)

#aplicamos filtro de columnas para filtrar las columnas con variables numéricas (se descartaron las columnas que muestran números de telofóno y las coordenadas) 
Retailers_Filtrado1=Retailers_Filtrado.iloc[:,[13,14,16,21,22,29,31,33,42,49,51,56,57,58,59,60,78,90,]]#columnas no consecutivas
Retailers_Filtrado1

"""# Se aplica método de cuatiles para sustitución de outliers"""

#Método aplicando Cuartiles. Encuentro cuartiles 0.25 y 0.75
y=Retailers_Filtrado1

percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

#Encontramos Outliers del Dataframe
outliers_iqr= Retailers_Filtrado1[(y>Limite_Superior_iqr)|(y<Limite_Inferior_iqr)]
outliers_iqr

#Obtenemos datos limpios del Dataframe
data3_iqr= Retailers_Filtrado1[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3_iqr

#Corroboramos valores nulos del dataframe LIMPIO
valores_nulos=data3_iqr.isnull().sum()
valores_nulos

#Reemplazamos valores atípicos (nulos) del dataframe con "mean"
#Realizamos una copia del dataframe
data4_iqr=data3_iqr.copy()
data4_iqr=data4_iqr.fillna(round(data3_iqr.mean(),1))
data4_iqr

Retailers_Filtrado2=data4_iqr.copy()

c

#convertir a archivo xlsx
Retailers_Filtrado2.to_excel("Retailers_Sin_Outliers.xlsx")

#descargar archivo filtrado en xlsx
from google.colab import files
files.download("Retailers_Sin_Outliers.xlsx")

